// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AgentStatus int32

const (
	AgentStatus_Status1 AgentStatus = 0
	AgentStatus_Status2 AgentStatus = 1
	AgentStatus_Status3 AgentStatus = 2
)

var AgentStatus_name = map[int32]string{
	0: "Status1",
	1: "Status2",
	2: "Status3",
}

var AgentStatus_value = map[string]int32{
	"Status1": 0,
	"Status2": 1,
	"Status3": 2,
}

func (x AgentStatus) String() string {
	return proto.EnumName(AgentStatus_name, int32(x))
}

func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

type AppSign struct {
	Devphyid             string   `protobuf:"bytes,1,opt,name=devphyid,proto3" json:"devphyid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppSign) Reset()         { *m = AppSign{} }
func (m *AppSign) String() string { return proto.CompactTextString(m) }
func (*AppSign) ProtoMessage()    {}
func (*AppSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *AppSign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppSign.Unmarshal(m, b)
}
func (m *AppSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppSign.Marshal(b, m, deterministic)
}
func (m *AppSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppSign.Merge(m, src)
}
func (m *AppSign) XXX_Size() int {
	return xxx_messageInfo_AppSign.Size(m)
}
func (m *AppSign) XXX_DiscardUnknown() {
	xxx_messageInfo_AppSign.DiscardUnknown(m)
}

var xxx_messageInfo_AppSign proto.InternalMessageInfo

func (m *AppSign) GetDevphyid() string {
	if m != nil {
		return m.Devphyid
	}
	return ""
}

type AppSignResponse struct {
	Retcode              int32    `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Retmsg               string   `protobuf:"bytes,2,opt,name=retmsg,proto3" json:"retmsg,omitempty"`
	Devphyid             string   `protobuf:"bytes,3,opt,name=devphyid,proto3" json:"devphyid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppSignResponse) Reset()         { *m = AppSignResponse{} }
func (m *AppSignResponse) String() string { return proto.CompactTextString(m) }
func (*AppSignResponse) ProtoMessage()    {}
func (*AppSignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *AppSignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppSignResponse.Unmarshal(m, b)
}
func (m *AppSignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppSignResponse.Marshal(b, m, deterministic)
}
func (m *AppSignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppSignResponse.Merge(m, src)
}
func (m *AppSignResponse) XXX_Size() int {
	return xxx_messageInfo_AppSignResponse.Size(m)
}
func (m *AppSignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppSignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppSignResponse proto.InternalMessageInfo

func (m *AppSignResponse) GetRetcode() int32 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

func (m *AppSignResponse) GetRetmsg() string {
	if m != nil {
		return m.Retmsg
	}
	return ""
}

func (m *AppSignResponse) GetDevphyid() string {
	if m != nil {
		return m.Devphyid
	}
	return ""
}

func init() {
	proto.RegisterEnum("AgentStatus", AgentStatus_name, AgentStatus_value)
	proto.RegisterType((*AppSign)(nil), "AppSign")
	proto.RegisterType((*AppSignResponse)(nil), "AppSignResponse")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0x8a, 0x49, 0x3b, 0x45, 0x1a, 0xf6, 0x20, 0xa1, 0x07, 0x91, 0x80, 0x22, 0x1e,
	0x36, 0xd8, 0x0a, 0x9e, 0x3c, 0xb4, 0x08, 0xbd, 0xa7, 0x78, 0xf1, 0x22, 0x71, 0x32, 0xac, 0x0b,
	0x66, 0x67, 0xd8, 0xac, 0x15, 0xff, 0xbd, 0x34, 0x8d, 0x96, 0x7a, 0xda, 0xfd, 0x98, 0x8f, 0x79,
	0x8f, 0x81, 0x71, 0x25, 0xa2, 0xc5, 0x73, 0xe0, 0xfc, 0x0a, 0x92, 0xa5, 0xc8, 0xc6, 0x1a, 0xa7,
	0x66, 0x30, 0xaa, 0x69, 0x2b, 0xef, 0xdf, 0xb6, 0xce, 0xa2, 0xcb, 0xe8, 0x66, 0x5c, 0xfe, 0x71,
	0xfe, 0x0a, 0xd3, 0x5e, 0x2b, 0xa9, 0x15, 0x76, 0x2d, 0xa9, 0x0c, 0x12, 0x4f, 0x01, 0xb9, 0xa6,
	0xce, 0x3e, 0x2d, 0x7f, 0x51, 0x9d, 0x43, 0xec, 0x29, 0x34, 0xad, 0xc9, 0x86, 0xdd, 0x9a, 0x9e,
	0x8e, 0x02, 0x4e, 0x8e, 0x03, 0x6e, 0xef, 0x61, 0xb2, 0x34, 0xe4, 0xc2, 0x26, 0x54, 0xe1, 0xb3,
	0x55, 0x13, 0x48, 0xf6, 0xbf, 0xbb, 0x74, 0x70, 0x80, 0x79, 0x1a, 0x1d, 0x60, 0x91, 0x0e, 0xe7,
	0x0f, 0x70, 0xd6, 0xd7, 0x7a, 0xa2, 0xad, 0x45, 0x52, 0xd7, 0x10, 0xef, 0xc8, 0x3a, 0x35, 0xd2,
	0xfd, 0x64, 0x96, 0xea, 0x7f, 0xd5, 0xf3, 0xc1, 0xea, 0x11, 0xa6, 0xc8, 0x8d, 0x36, 0x5e, 0x50,
	0x1b, 0xae, 0xa9, 0xe1, 0x15, 0xac, 0x79, 0xed, 0x05, 0x9f, 0x83, 0xfd, 0x78, 0xb9, 0x70, 0xf4,
	0x85, 0x95, 0x10, 0x6a, 0xe4, 0xa6, 0xd8, 0x59, 0xc5, 0xde, 0x2a, 0xba, 0xab, 0xbd, 0xc5, 0xdd,
	0xb3, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0x44, 0x05, 0x4d, 0x0a, 0x49, 0x01, 0x00, 0x00,
}
