// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: app.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AppSignDeviceClient is the client API for AppSignDevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppSignDeviceClient interface {
	Signin(ctx context.Context, in *AppSign, opts ...grpc.CallOption) (*AppSignResponse, error)
}

type appSignDeviceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppSignDeviceClient(cc grpc.ClientConnInterface) AppSignDeviceClient {
	return &appSignDeviceClient{cc}
}

func (c *appSignDeviceClient) Signin(ctx context.Context, in *AppSign, opts ...grpc.CallOption) (*AppSignResponse, error) {
	out := new(AppSignResponse)
	err := c.cc.Invoke(ctx, "/AppSignDevice/Signin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppSignDeviceServer is the server API for AppSignDevice service.
// All implementations must embed UnimplementedAppSignDeviceServer
// for forward compatibility
type AppSignDeviceServer interface {
	Signin(context.Context, *AppSign) (*AppSignResponse, error)
	mustEmbedUnimplementedAppSignDeviceServer()
}

// UnimplementedAppSignDeviceServer must be embedded to have forward compatible implementations.
type UnimplementedAppSignDeviceServer struct {
}

func (UnimplementedAppSignDeviceServer) Signin(context.Context, *AppSign) (*AppSignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signin not implemented")
}
func (UnimplementedAppSignDeviceServer) mustEmbedUnimplementedAppSignDeviceServer() {}

// UnsafeAppSignDeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppSignDeviceServer will
// result in compilation errors.
type UnsafeAppSignDeviceServer interface {
	mustEmbedUnimplementedAppSignDeviceServer()
}

func RegisterAppSignDeviceServer(s grpc.ServiceRegistrar, srv AppSignDeviceServer) {
	s.RegisterService(&AppSignDevice_ServiceDesc, srv)
}

func _AppSignDevice_Signin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppSign)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppSignDeviceServer).Signin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AppSignDevice/Signin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppSignDeviceServer).Signin(ctx, req.(*AppSign))
	}
	return interceptor(ctx, in, info, handler)
}

// AppSignDevice_ServiceDesc is the grpc.ServiceDesc for AppSignDevice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppSignDevice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AppSignDevice",
	HandlerType: (*AppSignDeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signin",
			Handler:    _AppSignDevice_Signin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}
